site:
    baseUrl: http://localhost:3000/
    language: en-US
    title: The AWS Developers Podcast
    description: Seb and friends chat with the people behind Amazon Web Services (AWS) and the developers who are building on it
    dateFormat: "yyyy-MM-dd HH:mm:ss Z"

themes:
    use: "default"
    folder: "themes"
    templates:
        folder: "templates"
    assets:
        folder: "assets"
    overrides:
        folder: "theme_overrides"

types:
    folder: "types"

content:
    folder: "content"
    assets:
        folder: "assets"

userDefined:
    podcast:
        feed: true
    downloadUrl: http://www.podtrac.com/pts/redirect.mp3/developers.podcast.go-aws.com/media/
    apple:
        podcastId: id1574162669
    
