site:
    baseUrl: http://localhost:3000/
    language: en-US
    title: The AWS Developers Podcast
    description: Seb and friends chat with the people behind Amazon Web Services (AWS) and the developers who are building on it
    dateFormat: "yyyy.MM.dd. HH:mm"

contents:
    blog:
        authors:
            folder: "podcast/authors"
            slugPrefix: "authors"
        tags:
            folder: "podcast/tags"
            slugPrefix: "podcasts"
        posts:
            folder: "podcast/episodes"
            slugPrefix: "podcasts/episodes"
    pages:
        custom:
            folder: "pages/custom"
            slugPrefix: ""

pages:
    main:
        home:
            path: "pages/home"
        notFound:
            path: "pages/404"
    blog:
        home:
            path: "pages/blog/home"
        authors:
            path: "pages/blog/authors"
        tags:
            path: "pages/blog/tags"
        posts:
            path: "pages/blog/posts"

userDefined:
    apple:
        podcastId: id1574162669
