site:
    baseUrl: http://localhost:3000/
    language: en-US
    title: Swift on server
    description: Articles about server-side Swift development. Created by Joannis Orlandos and Tibor Bödecs.
    dateFormat: "yyyy.MM.dd. HH:mm"

themes:
    use: "default"
    folder: "themes"
    templates:
        folder: "templates"
    assets:
        folder: "assets"
    overrides:
        folder: "theme_overrides"

types:
    folder: "types"

content:
    folder: "content"
    assets:
        folder: "assets"
