site:
    baseUrl: http://localhost:3000/
    language: en-US
    title: Scientific Titans Blog
    description: This is a demo blog using completely fake content.
    dateFormat: "yyyy.MM.dd. HH:mm"
    noindex: false
    hreflang:
        - lang: en
          url: https://www.example.com/
        - lang: en-gb
          url: https://www.example.com/gb/
        - lang: x-default
          url: https://www.example.com/

themes:
    use: "default"
    folder: "themes"
    templates:
        folder: "templates"
    assets:
        folder: "assets"
    overrides:
        folder: "theme_overrides"

types:
    folder: "types"

content:
    folder: "content"
    assets:
        folder: "assets"
