site:
    baseUrl: http://localhost:3000/
    language: en-US
    title: The.Swift.Dev.
    description: Articles about server-side Swift application development.
    dateFormat: "yyyy/MM/dd"
    noindex: false

themes:
    use: "default"
    folder: "themes"
    templates:
        folder: "templates"
    assets:
        folder: "assets"
    overrides:
        folder: "theme_overrides"

types:
    folder: "types"

content:
    folder: "content"
    assets:
        folder: "assets"
